# Generated by Django 3.2.14 on 2022-07-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_actif', models.BooleanField()),
                ('promo_code', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surface', models.FloatField()),
                ('number_of_pieces', models.IntegerField()),
                ('features', models.TextField(blank=True)),
                ('id_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prog', to='api_app.program')),
            ],
        ),
    ]
